* Quotes
Quotes once impressed me.

** No. 006 (12/04/2016)
#+BEGIN_QUOTE
Say to them,
say to the down-keepers,
the sun-slappers,
the self-soilers,
the harmony-hushers,
"even if you are not ready for day
it cannot always be night."
You will be right.
For that is the hard home-run.

Live not for battles won.
Live not for the-end-of-the-song.
Live in the along.

-- Speech To The Young : Speech To The Progress-Toward - Poem by Gwendolyn Brooks

#+END_QUOTE
** No. 005 (11/05/2016)
#+BEGIN_QUOTE
人所拥有的任何东西，都可以被剥夺，唯独人性最后的自由---也就是在任何境遇中选择一己态度和生活方式的自由---不能被剥夺。

-- /Viktor Emil Frankl, Man's Searching For Meaning/

Everything can be taken from a man but one thing: the last of the human freedom --- to choose one's attitude in any given set of circumstances, to choose one's own way.
#+END_QUOTE
** No. 004 (10/29/2016)
#+BEGIN_QUOTE
The rights and privileges of first-class citizens

- to be named by variables.
- to be passed as arguments to procedures.
- to be returned as values of procedures.
- to be incorporated into data structures.

-- /Lecture2A_MIT 6.001 Structure and Interpretation of Computer Programs/
#+END_QUOTE
** No. 003 (10/26/2016)
#+BEGIN_QUOTE
New and shiny is what clients want, boring and dependable is what owners want.

-- Hacker News comments on /Happiness is a Boring Stack/
#+END_QUOTE

** No. 002 (10/25/2016)
#+BEGIN_QUOTE
Been telling myself, all I need is 20 seconds of insane courage and something amazing will happen.

- All I need is 20 seconds of insane courage, to put on my running shoes.
- All I need is 20 seconds of insane courage, to make that phone call to potential customers.
- All I need is 20 seconds of insane courage, to ask for a date.

20 seconds, never been easier for me.

-- Movie /We Bought a Zoo/
#+END_QUOTE

** No. 001 (10/24/2016)
#+BEGIN_QUOTE
The key to understanding complicated things is knowing what not to look at,
not to compute, not to think.

-- Genald Jay Sussman
#+END_QUOTE
